### ISSUE TITLE
FindNearby Project Readme Update.

### ISSUE THREAD

**Issue by Dhorse** [forcedotcom/LWC-Mobile-Samples#119]
Hello,

We had an issue where the Find Nearby App was not working on Salesforce Offline Mobile App.  On a call with Salesforce it was determined that the documentation was incomplete.  Step 6 in the readme file on the Find Nearby Project mentions to add a Trusted URL for "maps.a.forceusercontent.com".  This needs to be updated to add a Trusted URL for "maps.a.forceusercontent.com" AND "maps.b.forceusercontent.com".

More Discussion on this can be found here:
https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007T2PQ9SAN

**Comment by maliroteh-sf** [comment]
FYI @rotem-hen-sf Please review this issue & the suggested solution. Thx

**Comment by rotem-hen-sf** [comment]
Thanks @maliroteh-sf, I added this info, and also fixed an indentation issue.
Please approve the PR: https://github.com/forcedotcom/LWC-Mobile-Samples/pull/121
